name: Update PlatformIO Libraries

on:
  schedule:
    - cron: '0 15 * * 1' # Runs weekly on mondays at 3p.m..
  workflow_dispatch: # Allow manual triggering

jobs:
  update:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ ubuntu-latest ]

    steps:
      - uses: actions/checkout@v3
      - uses: actions/cache@v3
        with:
          path: |
            ~/.cache/pip
            ~/.platformio/.cache
          key: ${{ runner.os }}-pio

      - name: Install PlatformIO Core
        run: python -m pip install -U platformio

      - name: Update Libraries
        run: |
          pio lib update
          git config --global user.name 'GitHub Action'
          git config --global user.email 'action@github.com'
          git add platformio.ini
          git commit -m "[DEPS-UPDATE] Update PlatformIO libraries"
          git push
